---
title: "EDA"
output: html_document
runtime: shiny
---

This R Markdown file contains the EDA for the Kaggle competition [predicting Russian house prices](https://www.kaggle.com/c/sberbank-russian-housing-market#evaluation).

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(shiny)
library(dygraphs)
```

Read in train data. It's has a lot of variables

```{r}
train <- read.csv("train.csv", stringsAsFactors = FALSE)
```

Histograms of numeric variables

```{r, echo = FALSE}
train_classes <- map_chr(train, class)
train_numerics <- train_classes[train_classes %in% c("integer","numeric")] %>% names

sliderInput("quantile", "select quantiles:", 
            min = 0, max = 100, value = c(0, 98))

renderPlot({
  qnt <- as.numeric(quantile(train$price_doc, probs = input$quantile/100))
  
  train$price_doc[train$price_doc <= qnt] %>% 
    hist(main="Histogram of price_doc")
})

selectInput("train_var", "select variable to compare with `price_doc`:", 
          train_numerics[train_numerics != "id"])

renderPlot({
  index <- which(names(train) == input$train_var)
  plot_data <- as.numeric(unlist(train[index]))
  
  qnt <- as.numeric(quantile(plot_data, probs = input$quantile/100,
                             na.rm = TRUE))
  
  plot_data[plot_data <= qnt] %>% 
    hist(main=paste("Histogram of",input$train_var))
})
```

Feature generating function to be applied to both the training and test data

```{r}
generate_features <- function(df){
  df$timestamp <- as.Date(df$timestamp)
  df$day <- weekdays(df$timestamp)
  df$month <- months(df$timestamp)
  df
}
```

```{r}
train <- generate_features(train)
test <- generate_features(test)
```


```{r, message=FALSE}
#macro <- read.csv("macro.csv", stringsAsFactors = FALSE)
```

```{r}
test <- read.csv("test.csv", stringsAsFactors = F)
```

